package healthins;

import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author vitormgb
 */
public class calendarPanel extends javax.swing.JFrame {

    /**
     * Creates new form UserContent
     */
    public calendarPanel() {
        initComponents();
        setDefaultCloseOperation(RegisterFrame.DISPOSE_ON_CLOSE);
        getImages();
    }
    
    public static ArrayList<Calendar> readCalendarList(ArrayList <Calendar> calendar){
        try{
            InputStream file = new FileInputStream("calendar");
            InputStream buffer = new BufferedInputStream(file);
            File f = new File("calendar");
            if(f.length()!=0){
                try(ObjectInput input = new ObjectInputStream (buffer)) {
                    ArrayList<Calendar> recoveredCal = (ArrayList<Calendar>)input.readObject();
                    for(Calendar c: recoveredCal)
                       calendar.add(new Calendar(c.getDay(), c.getMonth(), c.getDescription(), c.getOwner(), c.getName()));
                }
            }
        }
        catch(ClassNotFoundException | IOException ex){
            return null;
        }
        return calendar;
    }
    
    public static Boolean saveCalendarList(ArrayList <Calendar> calendar){
        try {
            FileOutputStream fos = new FileOutputStream("calendar");
            try (ObjectOutputStream oos = new ObjectOutputStream(fos)) {
                oos.writeObject(calendar);
            }
        }
        catch(IOException ex) {
            return false;
        }
        return true; 
    }

    private void getImages() {
        try {
            BufferedImage calendarIcon = ImageIO.read(new File("imgs/cal.png"));
            BufferedImage contactIcon = ImageIO.read(new File("imgs/cont.png"));
            BufferedImage formIcon = ImageIO.read(new File("imgs/serv.png"));
            BufferedImage historyIcon = ImageIO.read(new File("imgs/hist.png"));
            BufferedImage calcIcon = ImageIO.read(new File("imgs/calc.png"));

            JLabel calLabel = new JLabel(new ImageIcon(calendarIcon));
            JLabel contactLabel = new JLabel(new ImageIcon(contactIcon));
            JLabel formLabel = new JLabel(new ImageIcon(formIcon));
            JLabel histLabel = new JLabel(new ImageIcon(historyIcon));
            JLabel calcLabel = new JLabel(new ImageIcon(calcIcon));

            this.calendarPanel.add(calLabel);
            this.contactPanel.add(contactLabel);
            this.formPanel.add(formLabel);
            this.historyPanel.add(histLabel);
            this.calcPanel.add(calcLabel);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Unable to load images.");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPanel = new javax.swing.JTabbedPane();
        calendarPanel = new javax.swing.JTabbedPane();
        contactPanel = new javax.swing.JTabbedPane();
        historyPanel = new javax.swing.JTabbedPane();
        logoutButton = new javax.swing.JButton();
        calcPanel = new javax.swing.JTabbedPane();
        dayComboBox = new javax.swing.JComboBox();
        MonthComboBox = new javax.swing.JComboBox();
        loadMonthButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        loadDayButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        newAppointmentArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eventNameBox = new javax.swing.JTextField();
        editEventButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        formPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formPanelMouseClicked(evt);
            }
        });

        calendarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarPanelMouseClicked(evt);
            }
        });

        contactPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactPanelMouseClicked(evt);
            }
        });

        historyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyPanelMouseClicked(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        calcPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcPanelMouseClicked(evt);
            }
        });

        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboBoxActionPerformed(evt);
            }
        });

        MonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        loadMonthButton.setText("Load Month");
        loadMonthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadMonthButtonMouseClicked(evt);
            }
        });
        loadMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMonthButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        loadDayButton.setText("Load Day");
        loadDayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadDayButtonMouseClicked(evt);
            }
        });

        newAppointmentArea.setColumns(20);
        newAppointmentArea.setRows(5);
        newAppointmentArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newAppointmentAreaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(newAppointmentArea);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("New Appointment");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Event Name");

        editEventButton.setText("Edit Event");
        editEventButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editEventButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadMonthButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadDayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editEventButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(contactPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(calcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MonthComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historyPanel)
                    .addComponent(contactPanel)
                    .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(calcPanel))
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loadMonthButton)
                            .addComponent(deleteButton)
                            .addComponent(loadDayButton)
                            .addComponent(saveButton)
                            .addComponent(editEventButton))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        this.setVisible(false);
        Login frame = new Login(Login.users);
        frame.setSize(400, 400);
        frame.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void formPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formPanelMouseClicked
        this.dispose();
        this.setVisible(false);
        formPanel frame = new formPanel();
        frame.setVisible(true);
    }//GEN-LAST:event_formPanelMouseClicked

    private void calendarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarPanelMouseClicked
        
    }//GEN-LAST:event_calendarPanelMouseClicked

    private void contactPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactPanelMouseClicked
        this.dispose();
        this.setVisible(false);
        contactPanel frame = new contactPanel();
        frame.setVisible(true);
    }//GEN-LAST:event_contactPanelMouseClicked

    private void calcPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcPanelMouseClicked
        this.dispose();
        this.setVisible(false);
        calculatorPanel frame = new calculatorPanel();
        frame.setVisible(true);
    }//GEN-LAST:event_calcPanelMouseClicked

    private void dayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboBoxActionPerformed
       
    }//GEN-LAST:event_dayComboBoxActionPerformed

    private void loadMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMonthButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadMonthButtonActionPerformed

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        ArrayList<Calendar> cal = new ArrayList();
        cal = readCalendarList(cal);
        String month = (String) this.MonthComboBox.getSelectedItem();
        String day = (String) this.dayComboBox.getSelectedItem();
        String desc;
        String eName = "";
        try{
            eName = this.eventNameBox.getText();
        } catch(Exception e){
            
        }
        if(checkDate(day,month)){
            if(!isScheduled(month,day,eName)){
                try{
                    desc = this.newAppointmentArea.getText();
                    if(desc.length()!=0 && eName.length()!=0){
                        cal.add(new Calendar(day, month, desc, HealthIns.currentUsr.getId(), eName));
                        saveCalendarList(cal);
                        JOptionPane.showMessageDialog(null,"Appointment added at "+day+"/"+month);
                        this.newAppointmentArea.setText("");
                        this.eventNameBox.setText("");
                    }
                    else
                        JOptionPane.showMessageDialog(null,"All the events must contain name and description!"); 
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"All the events must contain name and description!"); 
                }
            }
            else
                JOptionPane.showMessageDialog(null,"This event has already been added on this day!"); 
        }
        else
            JOptionPane.showMessageDialog(null,"Invalid date format!"); 
    }//GEN-LAST:event_saveButtonMouseClicked

    private void loadMonthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadMonthButtonMouseClicked
        ArrayList<Calendar> cal = new ArrayList();
        cal = readCalendarList(cal);
        String month = (String) this.MonthComboBox.getSelectedItem();
        String finaltext="";
        String line = "------------------------------------------------------------------\n";
        if(checkDate("1",month)){
            for(int i=0; i<cal.size(); i++){
                if(cal.get(i).getMonth().equalsIgnoreCase(month) 
                        && cal.get(i).getOwner().equals(HealthIns.currentUsr.getId())){
                    finaltext += line + cal.get(i).getDay()+"\t"+cal.get(i).getMonth()+"\n\n"+"Event: "+cal.get(i).getName()+
                            "\n\nDescription\n"+cal.get(i).getDescription()+"\n"+line;
                }
            }
            if(finaltext.equals(""))
                JOptionPane.showMessageDialog(null,"No appointments scheduled for this month.");
            else
                JOptionPane.showMessageDialog(null,finaltext);
        }    
        else
           JOptionPane.showMessageDialog(null,"Invalid date format!");  
    }//GEN-LAST:event_loadMonthButtonMouseClicked

    private void loadDayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadDayButtonMouseClicked
        ArrayList<Calendar> cal = new ArrayList();
        cal = readCalendarList(cal);
        String month = (String) this.MonthComboBox.getSelectedItem();
        String day = (String) this.dayComboBox.getSelectedItem();
        String finaltext="";
        String line = "------------------------------------------------------------------\n";
        if(checkDate(day,month)){
            for(int i=0; i<cal.size(); i++){
                if(cal.get(i).getDay().equals(day) && cal.get(i).getMonth().equalsIgnoreCase(month) 
                        && cal.get(i).getOwner().equals(HealthIns.currentUsr.getId())){
                    finaltext += line + cal.get(i).getDay()+"\t"+cal.get(i).getMonth()+"\n\n"+"Event: "+cal.get(i).getName()+
                            "\n\nDescription\n"+cal.get(i).getDescription()+"\n"+line;
                }
            }
            if(finaltext.equals(""))
                JOptionPane.showMessageDialog(null,"No appointments scheduled for this day.");
            else
                JOptionPane.showMessageDialog(null,finaltext);
        }    
        else
           JOptionPane.showMessageDialog(null,"Invalid date format!");  
    }//GEN-LAST:event_loadDayButtonMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        ArrayList<Calendar> cal = new ArrayList();
        cal = readCalendarList(cal);
        boolean found = false;
        String month = (String) this.MonthComboBox.getSelectedItem();
        String day = (String) this.dayComboBox.getSelectedItem();
        String eName = "";
        try{
            eName = this.eventNameBox.getText();
        } catch(Exception e){
            
        }
        if(checkDate(day,month) && !eName.equals("")){
            for(int i=0; i<cal.size(); i++){
                if(cal.get(i).getDay().equalsIgnoreCase(day) && cal.get(i).getMonth().equalsIgnoreCase(month) 
                        && cal.get(i).getOwner().equals(HealthIns.currentUsr.getId()) && cal.get(i).getName().equalsIgnoreCase(eName)){
                    cal.remove(i);
                    saveCalendarList(cal);
                    JOptionPane.showMessageDialog(null,"Appointment deleted!");
                    found = true;
                    this.eventNameBox.setText("");
                    break;
                }
            }
        }
        else{
           JOptionPane.showMessageDialog(null,"Invalid date format or event name!"); 
           found = true;
        }
        if(!found)
            JOptionPane.showMessageDialog(null,"Appointment not found!");
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void newAppointmentAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newAppointmentAreaMouseClicked
        
    }//GEN-LAST:event_newAppointmentAreaMouseClicked

    private void historyPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyPanelMouseClicked
        this.dispose();
        this.setVisible(false);
        historyPanel frame = new historyPanel();
        frame.setSize(640, 405);
        frame.setVisible(true);
    }//GEN-LAST:event_historyPanelMouseClicked

    private void editEventButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEventButtonMouseClicked
        ArrayList<Calendar> cal = new ArrayList();
        cal = readCalendarList(cal);
        String month = (String) this.MonthComboBox.getSelectedItem();
        String day = (String) this.dayComboBox.getSelectedItem();
        String eName = "";
        this.newAppointmentArea.setText("");
        try{
            eName = this.eventNameBox.getText();
        } catch(Exception e){
            
        }
        if(checkDate(day,month) && eName.length()!=0){
            for (int i=0; i<cal.size(); i++){
                if(cal.get(i).getDay().equals(day) && cal.get(i).getMonth().equals(month)
                    && cal.get(i).getName().equalsIgnoreCase(eName) && cal.get(i).getOwner().equals(HealthIns.currentUsr.getId())){
                    this.newAppointmentArea.append(cal.get(i).getDescription()+"\n");
                    cal.remove(i);
                    saveCalendarList(cal);
                }
            } 
        }
        else
            JOptionPane.showMessageDialog(null,"Invalid date format or event name!");
    }//GEN-LAST:event_editEventButtonMouseClicked

    private boolean checkDate(String day, String month){
        if(!day.equalsIgnoreCase("day")){
            int d = Integer.parseInt(day);
            if(month.equalsIgnoreCase("month") || day.equalsIgnoreCase("day"))
                return false;
            if (month.equals("February") && d>29)
                return false;
            else if(month.equals("April") || month.equals("June") || month.equals("September") || month.equals("November"))
                 return d != 31;
            return true;
        }
        else
            return false;
        
    }
    
    private boolean isScheduled(String month, String day, String name){
        ArrayList<Calendar> cal = new ArrayList();
        cal = readCalendarList(cal);
        String currentUser = HealthIns.currentUsr.getId();
        for (int i=0; i<cal.size(); i++){
            if(cal.get(i).getDay().equals(day) && cal.get(i).getMonth().equals(month) &&  cal.get(i).getName().equalsIgnoreCase(name)
                    && cal.get(i).getOwner().equals(currentUser))
                return true;
        }
        return false;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calendarPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new calendarPanel().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MonthComboBox;
    private javax.swing.JTabbedPane calcPanel;
    private javax.swing.JTabbedPane calendarPanel;
    private javax.swing.JTabbedPane contactPanel;
    private javax.swing.JComboBox dayComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editEventButton;
    private javax.swing.JTextField eventNameBox;
    private javax.swing.JTabbedPane formPanel;
    private javax.swing.JTabbedPane historyPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadDayButton;
    private javax.swing.JButton loadMonthButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextArea newAppointmentArea;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
