package healthins;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author vitormgb
 */
public class UserContent extends javax.swing.JFrame {

    /**
     * Creates new form UserContent
     */
    public UserContent() {
        initComponents();
        setDefaultCloseOperation(RegisterFrame.DISPOSE_ON_CLOSE);
        getImages();
    }

    private void getImages() {
        try {
            BufferedImage calendarIcon = ImageIO.read(new File("imgs/cal.png"));
            BufferedImage contactIcon = ImageIO.read(new File("imgs/cont.png"));
            BufferedImage formIcon = ImageIO.read(new File("imgs/serv.png"));
            BufferedImage historyIcon = ImageIO.read(new File("imgs/hist.png"));
            BufferedImage calcIcon = ImageIO.read(new File("imgs/calc.png"));

            JLabel calLabel = new JLabel(new ImageIcon(calendarIcon));
            JLabel contactLabel = new JLabel(new ImageIcon(contactIcon));
            JLabel formLabel = new JLabel(new ImageIcon(formIcon));
            JLabel histLabel = new JLabel(new ImageIcon(historyIcon));
            JLabel calcLabel = new JLabel(new ImageIcon(calcIcon));

            this.calendarPanel.add(calLabel);
            this.contactPanel.add(contactLabel);
            this.formPanel.add(formLabel);
            this.historyPanel.add(histLabel);
            this.calcPanel.add(calcLabel);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Unable to load images.");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPanel = new javax.swing.JTabbedPane();
        calendarPanel = new javax.swing.JTabbedPane();
        contactPanel = new javax.swing.JTabbedPane();
        historyPanel = new javax.swing.JTabbedPane();
        logoutButton = new javax.swing.JButton();
        calcPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formPanelMouseClicked(evt);
            }
        });

        calendarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarPanelMouseClicked(evt);
            }
        });

        contactPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactPanelMouseClicked(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        calcPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historyPanel)
                    .addComponent(contactPanel)
                    .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(calcPanel))
                .addGap(220, 220, 220)
                .addComponent(logoutButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        this.setVisible(false);
        Login frame = new Login(Login.users);
        frame.setSize(400, 400);
        frame.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void formPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formPanelMouseClicked
        this.dispose();
        this.setVisible(false);
        formPanel frame = new formPanel();
        frame.setVisible(true);
    }//GEN-LAST:event_formPanelMouseClicked

    private void calendarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarPanelMouseClicked
        
    }//GEN-LAST:event_calendarPanelMouseClicked

    private void contactPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactPanelMouseClicked
        this.dispose();
        this.setVisible(false);
        contactPanel frame = new contactPanel();
        frame.setVisible(true);
    }//GEN-LAST:event_contactPanelMouseClicked

    private void calcPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcPanelMouseClicked
        this.dispose();
        this.setVisible(false);
        calculatorPanel frame = new calculatorPanel();
        frame.setVisible(true);
    }//GEN-LAST:event_calcPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserContent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserContent().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane calcPanel;
    private javax.swing.JTabbedPane calendarPanel;
    private javax.swing.JTabbedPane contactPanel;
    private javax.swing.JTabbedPane formPanel;
    private javax.swing.JTabbedPane historyPanel;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
